### ISSUE TITLE
Annoying DeprecationWarning

### ISSUE THREAD

**Issue by g199209** [kedro-org/kedro#4818]
DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces.

This warning is stupid:

1. There's no `--namespaces` flag now, I can only use `--namespace`. I think we should support both new and old flags in transitional period, and show deprecation warning. But there's no new flag at all now!

2. I only use `kedro run` in command line, no `--namespace` or `--ns` flag at all, but still see this warning. I havn't find the reason why now.

**Comment by cramirez98** [comment]
Im having the same issue and im not using namespaces (just a plain kedro run --nodes=node).

**Comment by yury-fedotov** [comment]
+1, I find the "DataCatalog will be replaced by KedroDataCatalog" warning a bit noisy in the CLI output too, given that I don't use DataCatalog object explicitly in the Python API at all.

**Comment by ravi-kumar-pilla** [comment]
Hi, You can definitely reduce some noise using `export PYTHONWARNINGS="ignore::DeprecationWarning:kedro"`  in your run environment or you can also adjust the log level in logging.yml.

However, since this is coming from Kedro core, it is somewhat unavoidable at the moment. 

@ankatiyar are you aware of any better alternatives to reduce notifications mentioned above ? Thank you

**Comment by ankatiyar** [comment]
@ravi-kumar-pilla not off the top of my head apart from what you said!

@g199209 @cramirez98 @yury-fedotov The 1.0 release will be out soon, but the 1.0 pre-release is already out that you could start using :) https://pypi.org/project/kedro/1.0.0rc1/

**Comment by ravi-kumar-pilla** [comment]
Closing the issue as the workaround to get rid of the warnings is to upgrade Kedro version to 1.0.0rc1.

**Comment by g199209** [comment]
> [@ravi-kumar-pilla](https://github.com/ravi-kumar-pilla) not off the top of my head apart from what you said!
> 
> [@g199209](https://github.com/g199209) [@cramirez98](https://github.com/cramirez98) [@yury-fedotov](https://github.com/yury-fedotov) The 1.0 release will be out soon, but the 1.0 pre-release is already out that you could start using :) https://pypi.org/project/kedro/1.0.0rc1/

@ankatiyar Upgrade to 1.0.0rc1 doesn't solve this problem, still have this warning

**Comment by merelcht** [comment]
Hi @g199209 and @yury-fedotov, thanks for flagging the issue about these deprecation warnings being too noisy. 
I totally understand this is not a great experience and clutters your logs. We overlooked this while working hard to get the next major release out as soon as possible. 

I'm afraid we can't fix this within the `0.19.x` series anymore and the only thing you can do at the moment is downgrade your Kedro version to `0.19.11` when the warnings weren't added yet. Please bear with us while we work on bringing you Kedro `1.0.0` 🙏

**Comment by astrojuanlu** [comment]
Hi all, we've carefully considered this and we decided to do another 0.19 release, but after we have released 1.0. Please stay tuned and thanks for your patience!

**Comment by g199209** [comment]
> Hi all, we've carefully considered this and we decided to do another 0.19 release, but after we have released 1.0. Please stay tuned and thanks for your patience!

Are you sure 1.0 solve this problem? I have already upgrade to 1.0.0rc1, still see this warning.

**Comment by merelcht** [comment]
> Are you sure 1.0 solve this problem? I have already upgrade to 1.0.0rc1, still see this warning.

@g199209 Can you do a pip freeze to double check your Kedro version? The deprecation has been removed in `1.0.0rc1`. I've installed it and just double checked that the warning has indeed disappeared.

**Comment by ravi-kumar-pilla** [comment]
I also checked and I am not seeing any deprecation warnings. Thank you

**Comment by g199209** [comment]
> > Are you sure 1.0 solve this problem? I have already upgrade to 1.0.0rc1, still see this warning.
> 
> [@g199209](https://github.com/g199209) Can you do a pip freeze to double check your Kedro version? The deprecation has been removed in `1.0.0rc1`. I've installed it and just double checked that the warning has indeed disappeared.

Yes, `1.0.0rc1` solve it, but plugins like `kedro-mlflow` doesn't support 1.0.0rc1, so when I install these plugins, they auto roll kedro version back.

**Comment by astrojuanlu** [comment]
@g199209 We're working with downstream plugin authors, and specifically with kedro-mlflow, to make 1.0 compatibility a reality soon 🙏🏼

**Comment by DimedS** [comment]
The issue has been resolved with the recent [Kedro 0.19.15 release](https://github.com/kedro-org/kedro/pull/5062).  

In Kedro 0.19.15, the deprecation warning is now only shown when the `--namespace` flag is used.
